-- V3: 푸시 알림 테이블 (devices, notifications) — H2·PostgreSQL 공용 plain 컬럼

CREATE TABLE devices (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT       NOT NULL,
    fcm_token             VARCHAR(512) NOT NULL,
    platform              VARCHAR(10)  NOT NULL,
    latitude              DOUBLE PRECISION,
    longitude             DOUBLE PRECISION,
    location_updated_at   TIMESTAMP,
    nearby_alerts_enabled BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_device_token UNIQUE (fcm_token),
    CONSTRAINT fk_device_user  FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_device_user ON devices (user_id);

CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    type       VARCHAR(30)  NOT NULL,
    title      VARCHAR(255) NOT NULL,
    body       VARCHAR(500) NOT NULL,
    split_id   BIGINT,
    status     VARCHAR(20)  NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_notif_user_created ON notifications (user_id, created_at);
