-- V6: 신고(report) + 차단(block) — Phase 2 신뢰/안전 (H2·PostgreSQL 공용)

CREATE TABLE reports (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT       NOT NULL,
    target_type VARCHAR(20)  NOT NULL,   -- SPLIT | USER
    target_id   BIGINT       NOT NULL,
    reason      VARCHAR(30)  NOT NULL,   -- SPAM | FRAUD | INAPPROPRIATE | HARASSMENT | OTHER
    detail      VARCHAR(1000),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_report_reporter FOREIGN KEY (reporter_id) REFERENCES users (id)
);

CREATE INDEX idx_report_reporter ON reports (reporter_id);
CREATE INDEX idx_report_target   ON reports (target_type, target_id);

CREATE TABLE blocks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_id BIGINT    NOT NULL,
    blocked_id BIGINT    NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_block_blocker FOREIGN KEY (blocker_id) REFERENCES users (id),
    CONSTRAINT fk_block_blocked FOREIGN KEY (blocked_id) REFERENCES users (id),
    CONSTRAINT uk_block_pair UNIQUE (blocker_id, blocked_id)
);

CREATE INDEX idx_block_blocker ON blocks (blocker_id);
